name: parcel_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # --- YOUR ADDED PACKAGES ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # --- YOUR DEV PACKAGES ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true